from .eleccionViewSet import EleccionSerializer,EleccionViewSet
from .partidoViewSet import PartidoSerializer,PartidoViewSet
from .seccionViewSet import SeccionSerializer,SeccionViewSet
from .recintoViewSet import RecintoSerializer,RecintoViewSet
from .mesaViewSet import MesaSerializer,MesaViewSet
from .juradoViewSet import JuradoSerializer,JuradoViewSet
from .cargoViewSet import CargoSerializer,CargoViewSet
from .candidatoViewSet import CandidatoSerializer,CandidatoViewSet
