# Generated by Django 4.2.23 on 2025-06-23 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('geojson', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recinto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recintos', to='administracionElectoral.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Papeleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='papeletas/')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracionElectoral.eleccion')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracionElectoral.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('cantidad_votantes', models.IntegerField(default=0)),
                ('recinto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='administracionElectoral.recinto')),
            ],
        ),
        migrations.CreateModel(
            name='JuradoElectoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurados', to='administracionElectoral.mesa')),
            ],
        ),
        migrations.AddField(
            model_name='eleccion',
            name='secciones',
            field=models.ManyToManyField(related_name='elecciones', to='administracionElectoral.seccion'),
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('secciones', models.ManyToManyField(related_name='cargos', to='administracionElectoral.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='candidatos/')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracionElectoral.cargo')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracionElectoral.partido')),
            ],
        ),
    ]
