# Generated by Django 4.2.23 on 2025-06-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracionElectoral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recinto',
            name='cantidad_mesas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
