# Generated by Django 4.2.23 on 2025-06-26 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracionElectoral', '0002_recinto_cantidad_mesas'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesaVotante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=20)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votantes', to='administracionElectoral.mesa')),
            ],
        ),
    ]
