from .eleccion import Eleccion
from .seccion import Seccion
from .cargo import Cargo
from .recinto import Recinto
from .mesa import Mesa
from .jurado import JuradoElectoral
from .partido import Partido
from .candidato import Candidato
from .papeleta import Papeleta
from .mesaVotantes import MesaVotante
